### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by magamagaman1** [everythingishacked/Truthsayer#1]
Hi,
  What are the parameters to use for --input to use a window as the input for analysis?

Thanks, 

Leo.

**Comment by everythingishacked** [comment]
You can't directly specify an application window (that would start getting OS-dependent), but you can use a device, file path, or rectangle region of your screen.

From the README: `--input` - Choose a camera, video file path, or screen dimensions in the form `x y width height` - defaults to device `0`

So to grab the live contents of a window, you could i.e. place it in the top left of your screen and use something like `-i 0 0 400 200` to take repeated screenshots starting at top left (0, 0) for a width of 400 and height of 200 pixels.

**Comment by bac512** [comment]
is there any way to get audio in the recorded/marked up video (when running it on a video, there's no audio while it's playing or in the recording afterwards?
