### ISSUE TITLE
inputs

### ISSUE THREAD

**Issue by bac512** [everythingishacked/Truthsayer#6]
the only inputs I can get to work are linking to a file, and webcam.  and when I link to a file I can't scale the picture.  how do I make the screen input work?  I run the program (python intercept.py -l 1 -b 1 -r 1 -i 0,0,1920,1080)  it displays it's graph then just closes.

could you give some instructions on how to run this?

**Comment by everythingishacked** [comment]
I think you need spaces instead of commas for the screen dimensions.

From the README:
`--input` - Choose a camera, video file path, or screen dimensions in the form `x y width height`

So in your example:
`python intercept.py -l 1 -b 1 -r 1 -i 0 0 1920 1080`
